name: Build Obfuscate BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          npm install -g javascript-obfuscator
          sudo apt-get install -y unzip

      - name: Clean up old files
        run: |
          rm -f worker.zip _worker.js origin.js

      - name: Download and extract latest BPB worker
        run: |
          wget -O worker.zip https://github.com/bia-pain-bache/BPB-Worker-Panel/releases/download/v3.1.4/unobfuscated-worker.zip
          unzip -o worker.zip
          mv _worker.js origin.js

      - name: Obfuscate BPB worker js (simplified for Cloudflare)
        run: |
          javascript-obfuscator origin.js --output _worker.js \
          --compact true \
          --simplify true \
          --string-array false \
          --rename-globals false \
          --transform-object-keys false

      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest bpb panel'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
