name: Deploy Latest BPB Panel

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install -y unzip wget

      - name: Clean up old files
        run: rm -f worker.zip _worker.js origin.js

      - name: Download latest BPB Panel release
        run: |
          LATEST_URL=$(curl -s https://api.github.com/repos/bia-pain-bache/BPB-Worker-Panel/releases/latest \
            | grep "browser_download_url" \
            | grep "worker.zip" \
            | cut -d '"' -f 4)
          wget -O worker.zip "$LATEST_URL"

      - name: Unzip and rename for deployment
        run: |
          # 强制解压并处理文件名
          unzip -o worker.zip
          
          # 检查是否存在 _worker.js
          if [ ! -f "_worker.js" ]; then
            echo "⚠️ _worker.js not found, searching for JS files..."
            
            # 查找第一个 .js 文件并重命名
            js_file=$(find . -maxdepth 1 -name "*.js" -print -quit)
            
            if [ -z "$js_file" ]; then
              echo "❌ No JS files found in the zip!"
              exit 1
            fi

            echo "ℹ️ Renaming $js_file to _worker.js"
            cp "$js_file" origin.js    # 保存原始文件
            mv "$js_file" _worker.js   # 重命名为目标文件名
          else
            echo "✅ _worker.js already exists, backup as origin.js"
            cp _worker.js origin.js   # 备份原始文件
          fi

      - name: Commit updated _worker.js
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update to latest BPB worker (no obfuscation)'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
